version: '3.5'

services:
    postgres:
        image: postgres:14.6
        volumes:
            - postgres-db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD

volumes:
    postgres-db:

