version: '3.5'

services:
    mysql:
        image: percona:8.0
        volumes:
            - mysql-db:/var/lib/mysql
        environment:
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_ROOT_PASSWORD
            - MYSQL_ALLOW_EMPTY_PASSWORD
    postgres:
        image: postgres:14.6
        volumes:
            - postgres-db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD

volumes:
    mysql-db:
    postgres-db:

